### ISSUE TITLE
The first reading after `hdc.begin` is always incorrect

### ISSUE THREAD

**Issue by rzetterberg** [adafruit/Adafruit_HDC302x#2]
After running the function `hdc.begin`, the first reading returned by `hdc.readTemperatureHumidityOnDemand` is always `temperature = -45 °C` and `relative humidity = 0.00 %`, regardless of how long of a delay is used after `hdc.begin`.

I noticed this problem when I added a wait for serial to be connected in the example [HDC302x_basicTempHumidity.ino](https://github.com/adafruit/Adafruit_HDC302x/blob/9cb6c0b7f164962bbe12115d144e69f19c9046ab/examples/HDC302x_basicTempHumidity/HDC302x_basicTempHumidity.ino),
like so:

```c++
void setup() {
  Serial.begin(115200);

  Serial.println("Adafruit HDC302x Simple Test");

  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  if (! hdc.begin(0x44, &Wire)) {
    Serial.println("Could not find sensor?");
    while (1);
  }
  delay(1000);
}
```

Everytime I started the device, the first reading was always incorrect, but the rest of them were fine:

```
Temperature: -45.00 °C
Humidity: 0.00 %
Temperature: 22.13 °C
Humidity: 34.95 %
Temperature: 22.13 °C
Humidity: 35.00 %
Temperature: 22.13 °C
Humidity: 35.03 %
```

I've played around with different waiting times after `hdc.begin` was run to see if there's some form of initialization time that the sensor needed. But I encountered the same problem regardless of the waiting time used.

I also added a check to see whether `hdc.readTemperatureHumidityOnDemand` catches this first incorrect reading, by adding this to the example sketch:

```c++
  if(!hdc.readTemperatureHumidityOnDemand(temp, RH, TRIGGERMODE_LP0)) {
    Serial.println("Failed to read temperature/humidity");
    delay(2000);
    return;
  }
```

But that first reading does not produce a failure. I expected that function to return `false` if a reading like that was encountered.

# Environment

## Sketch

```c++
#include <Adafruit_HDC302x.h>

Adafruit_HDC302x hdc = Adafruit_HDC302x();

void setup() {
  Serial.begin(115200);

  Serial.println("Adafruit HDC302x Simple Test");

  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  if (! hdc.begin(0x44, &Wire)) {
    Serial.println("Could not find sensor?");
    while (1);
  }
  delay(1000);
}

void loop() {
  Serial.println("Trying to read temperature/humidity");

  double temp = 0.0;
  double RH = 0.0;

  if(!hdc.readTemperatureHumidityOnDemand(temp, RH, TRIGGERMODE_LP0)) {
    Serial.println("Failed to read temperature/humidity");
    delay(2000);
    return;
  }

  Serial.print("Temperature: ");
  Serial.print(temp);
  Serial.println(" °C");

  Serial.print("Humidity: ");
  Serial.print(RH);
  Serial.println(" %");
  delay(2000);
}
```

## Device

- Adafruit QT Py ESP32-S2 WiFi

## Arduino

```bash
$ arduino-cli version
arduino-cli  Version: 0.35.3 Commit: unknown Date:
```

## Libraries

```
$ arduino-cli lib list
Name                    Installed Available Location              Description
Adafruit BusIO          1.16.1    -         LIBRARY_LOCATION_USER -
Adafruit HDC302x        1.0.1     -         LIBRARY_LOCATION_USER -
Adafruit NeoPixel       1.12.3    -         LIBRARY_LOCATION_USER -
Adafruit Unified Sensor 1.1.14    -         LIBRARY_LOCATION_USER -
TinyWireM               1.1.3     -         LIBRARY_LOCATION_USER -
```

## Core

```bash
$ arduino-cli core list
ID          Installed Latest Name
esp32:esp32 3.0.5     3.0.5  esp32
```

**Comment by caternuson** [comment]
The datasheet says the device will NACK if an attempt is made to read the data before it is ready. However it shows this with a repeated start:
![image](https://github.com/user-attachments/assets/27a09e83-6d82-4f0b-92fc-5ccacd30a761)
It also does not specify how much time was waited before the second (successful) read was made.

Here's a scope trace of the current behavior:
![image](https://github.com/user-attachments/assets/904c3f7e-29fa-4a04-b645-5e8d249fdc29)
The library is **not** using repeated start. Although the read is done essentially instantly, the device does **not** NACK. Instead it just returns `0`'s 

In addition to the datasheet, TI also provides a [User Guide](https://www.ti.com/lit/pdf/snau265). This shows the reading being done without a repeated start:

![image](https://github.com/user-attachments/assets/c0f3e179-16a8-4562-87aa-32159cc44dde)

However, it does **not** provide any information about the timing or status checking between the trigger (write) and subsequent read.

Going back to datasheet, it does provide measurement timing information:
![image](https://github.com/user-attachments/assets/90706bce-57d2-45fc-b083-3e2151968efa)

Obviously, this driver is not waiting the required time. And since the HDC is not NACKing as expected, the wait-for-ready loop in the driver is not working as expected:
https://github.com/adafruit/Adafruit_HDC302x/blob/7d63fc60e2f9edd9d0eb1e121eb9a742d94552f6/Adafruit_HDC302x.cpp#L106-L108

**Comment by rzetterberg** [comment]
@caternuson thanks for the detailed info, it was super helpful!

I can confirm that your commit ef6a5f85970f59746970f877d2a59ef7cf8568cf solves the problem for me: 

```
Connected to /dev/ttyACM0! Press CTRL-C to exit.
Trying to read temperature/humidity
Temperature: 19.82 °C
Humidity: 32.99 %
Trying to read temperature/humidity
Temperature: 19.80 °C
Humidity: 32.93 %
```
